clase03/blog_scaffold/config/routes.rb
Rails.application.routes.draw do
  resources :posts

  resources :users, only: [:index, :show]

end

clase03/blog_scaffold/app/models/post.rb
class Post < ActiveRecord::Base

  validates :titulo, presence: true, length: { minimum: 5, maximum: 30, message: 'minimo 5 y maximo 30' }
  validates :contenido, presence: true


end

clase03/blog_scaffold/app/models/user.rb
# encoding: utf-8

class User < ActiveRecord::Base
  belongs_to :user_type

  validates :name, presence: true, format: { with: /\A(.*)/i , message: 'Sólo se acepta nombre que inicien con la letra J o j' }
  validates :username, uniqueness: true

  scope :has_user_type, -> { where('user_type_id IS NOT NULL') }

  scope :actives, -> {where(active: true)}

end

clase03/blog_scaffold/app/models/user_type.rb
class UserType < ActiveRecord::Base
  has_many :users
end

clase03/blog_scaffold/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_lang

  private

  def set_lang
    if params[:lang] == 'es'
      I18n.locale = :es
    else
      I18n.locale = :en
    end
  end

end

clase03/blog_scaffold/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  layout 'nuevo_layout'#, except: [:show]

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :contenido)
    end
end

clase03/blog_scaffold/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.has_user_type.actives
  end

end

clase03/blog_scaffold/app/helpers/application_helper.rb
module ApplicationHelper
end

clase03/blog_scaffold/app/helpers/posts_helper.rb
module PostsHelper

  def navigation_link link=nil, url
    link_to_if request.path != url, link, url
  end

end

clase03/blog_scaffold/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogScaffold</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='bg_green' >

<%= link_to 'Español', users_path(lang: 'es') %>

<%= link_to 'Inglés', users_path(lang: 'en') %>

<%= yield %>

</body>
</html>

clase03/blog_scaffold/app/views/layouts/nuevo_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogScaffold</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='bg_yellow'>

<h1>Jugando con Posts</h1>

<%= yield %>

</body>
</html>

clase03/blog_scaffold/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

clase03/blog_scaffold/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

clase03/blog_scaffold/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.titulo %></td>
        <td><%= post.contenido %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<%= navigation_link('Lista de Posts', posts_path) %>

clase03/blog_scaffold/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

clase03/blog_scaffold/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @post.contenido %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<%= navigation_link('Lista de Posts', posts_path) %>

clase03/blog_scaffold/app/views/users/index.html.erb
<h1><%= t(:users) %></h1>

<ul>
<% @users.each do |user| %>
  <li><%= user.name %> - <%= user.user_type.try(:name) %></li>
<% end %>
</ul>