clase01/blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  get 'posts/new'
  post 'posts' => 'posts#create'
  get 'posts/:id' => 'posts#show', as: :post
  get 'posts' => 'posts#index'
  get 'posts/:id/edit' => 'posts#edit'
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#destroy'

end

clase01/blog/app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, presence: true, length: { minimum: 5, maximum: 30, message: 'minimo 5 y maximo 30' }
  validates :text, presence: true

end

clase01/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

clase01/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts =  Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params

    if @post.save
      # show post
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find params[:id]
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]

    if @post.update post_params
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to action: :index
  end

  private

    def post_params
      params.require(:post).permit(:title, :text)
    end


end

clase01/blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

clase01/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

clase01/blog/app/helpers/posts_helper.rb
module PostsHelper
end

clase01/blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

clase01/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

clase01/blog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div class='errors'>
    <h2>Tiene <%= pluralize(@post.errors.count, 'error') %> </h2>

    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end%>
    </ul>
  </div>
  <% end %>
  <%= f.label 'Titulo' %>
  <%= f.text_field :title %>
  <br/>
  <br/>
  <br/>
  <%= f.label 'Texto' %>
  <%= f.text_area :text %>
  <br/>
  <br/>
  <br/>
  <br/>
  <%= f.submit %>
<% end %>

clase01/blog/app/views/posts/edit.html.erb
<h1>Editar Post</h1>
<%= render partial: 'form' %>

clase01/blog/app/views/posts/index.html.erb
<h1>Todos los posts</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Tetxo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.text %></td>
    <td><%= link_to 'Show', post_path(post)  %></td>
    <td><%= link_to 'Editar', action: :edit, id: post.id, method: :patch %></td>
    <td><%= link_to 'Eliminar', { action: :destroy, id: post.id }, method: :delete, data: { confirm: '¿Esta seguro de eliminar?'} %></td>
  </tr> 
<% end %>
</table>
<br />
<br />
<br />

<%= link_to 'Nuevo Post', posts_new_path %>

clase01/blog/app/views/posts/new.html.erb
<h1>Nuevo Post</h1>
<%= render partial: 'form' %>

clase01/blog/app/views/posts/show.html.erb
<p>
  <strong>Título:</strong>
  <%= @post.title %>
</p>
<p>
  <strong>Texto:</strong>
  <%= @post.text %>
</p>

<%= link_to 'Regresar', posts_path  %>

clase01/blog/app/views/welcome/index.html.erb
<h1>Yo amo Ruby on Rails <3</h1>